apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-chatbot-test-app-25-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-chatbot-test-app-25-gitops
    spec:
      serviceAccountName: chatbot-test-app-25-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=chatbot-test-app-25-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/chatbot-test-app-25-notebook -- git clone https://github.com/mvaldron-rhdh/chatbot-test-app-25
      restartPolicy: Never
